import { Mail, MessageCircle, RotateCcw, X } from "lucide-react";
import { useMemo, useState } from "react";

const RATE=150;
const LEVELS=[{pt:"Essencial",en:"Essential",m:.5},{pt:"Intermediário",en:"Standard",m:1},{pt:"Complexo",en:"Complex",m:1.5}];
const BRANCHES=[
  {id:"graphic",pt:"Design gráfico",en:"Graphic design",icon:"fox_8907474.svg",nodes:[{id:"identity",pt:"Identidade visual",en:"Visual identity",h:14,icon:"fox_8729898.svg"},{id:"logo",pt:"Logo",en:"Logo",h:10,icon:"fox_697191.svg"},{id:"mascot-concept",pt:"Conceito de mascote",en:"Mascot concept",h:6,icon:"fox_5511436.svg"},{id:"mascot-3d",pt:"Mascote 3D",en:"3D mascot",h:20,icon:"fox_502879.svg"},{id:"campaign",pt:"Campanha & social",en:"Campaign & social",h:8,icon:"fox_489994.svg"},{id:"editorial",pt:"Editorial & embalagem",en:"Editorial & packaging",h:14,icon:"fox_4631072.svg"}]},
  {id:"motion",pt:"Motion & 3D",en:"Motion & 3D",icon:"fox_3975050.svg",nodes:[{id:"animation-simple",pt:"Animação simples",en:"Simple animation",h:1,icon:"fox_3792068.svg"},{id:"social-motion",pt:"Motion para redes",en:"Social motion",h:6,icon:"fox_3704101.svg"},{id:"animation-piece",pt:"Peça animada",en:"Animated piece",h:10,icon:"fox_3616077.svg"},{id:"character",pt:"Animação de personagem",en:"Character animation",h:16,icon:"fox_311602.svg"},{id:"rig",pt:"Rig 2D / 3D",en:"2D / 3D rig",h:12,icon:"fox_2477621.svg"},{id:"titles",pt:"Vinheta & títulos",en:"Titles & opener",h:8,icon:"fox_2199876.svg"}]},
  {id:"code",pt:"Código & games",en:"Code & games",icon:"fox_2153090.svg",nodes:[{id:"portfolio",pt:"Site portfólio",en:"Portfolio website",h:12,icon:"fox_18499352.svg"},{id:"website",pt:"Site sob medida",en:"Custom website",h:30,icon:"fox_17554737.svg"},{id:"creative-code",pt:"Código criativo",en:"Creative coding",h:12,icon:"fox_12634954.svg"},{id:"automation",pt:"Automação",en:"Automation",h:8,icon:"fox-sitting_84155.svg"},{id:"game",pt:"Programação de jogo",en:"Game programming",h:40,icon:"fox_10748563.svg"},{id:"interactive",pt:"Experiência interativa",en:"Interactive experience",h:30,icon:"fox_8907474.svg"}]},
];
export default function QuotePlanner({open,onClose,locale}:{open:boolean;onClose:()=>void;locale:"pt-BR"|"en"}){
  const [started,setStarted]=useState(false),[branchId,setBranchId]=useState<string|null>(null),[serviceId,setServiceId]=useState<string|null>(null),[level,setLevel]=useState<number|null>(null); const en=locale==="en";
  const branch=BRANCHES.find(x=>x.id===branchId);const service=useMemo(()=>branch?.nodes.find(x=>x.id===serviceId),[branch,serviceId]);const money=(n:number)=>new Intl.NumberFormat(en?"en-US":"pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(n);const total=service&&level!==null?service.h*LEVELS[level].m*RATE:0;
  const restart=()=>{setStarted(false);setBranchId(null);setServiceId(null);setLevel(null)};const summary=`${en?"Quote request":"Pedido de orçamento"}\n${service?(en?service.en:service.pt):""}\n${level!==null?(en?LEVELS[level].en:LEVELS[level].pt):""}\n${en?"Estimated total":"Total estimado"}: ${money(total)}`;if(!open)return null;
  return <div className="modal-backdrop quote-tree-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="quote-tree-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}><X/></button><button className="tree-reset" onClick={restart}><RotateCcw/>{en?"Restart":"Recomeçar"}</button><p className="code-label">/ {en?"interactive quote":"orçamento interativo"}</p><h2>{en?"Find your":"Encontre seu"}<br/><em>{en?"path.":"caminho."}</em></h2><p>{en?"Choose one of the three categories — graphic design, motion / 3D or code — then follow the path until the final estimate.":"Escolha uma das três categorias — design gráfico, motion / 3D ou código — e siga o caminho até a estimativa final."}</p><div className="talent-tree"><svg viewBox="0 0 1000 430" preserveAspectRatio="none">{started&&!branch&&<path className="tree-line" d="M500 302 L500 225 L220 132 M500 225 L500 68 M500 225 L780 132"/>}{branch&&!service&&<path className="tree-line" d="M500 302 L500 68 M500 68 L150 180 M500 68 L340 258 M500 68 L500 318 M500 68 L660 258 M500 68 L850 180 M500 68 L500 138"/>}{service&&level===null&&<path className="tree-line" d="M500 302 L500 152 M500 152 L280 350 M500 152 L500 350 M500 152 L720 350"/>}</svg><button className={`tree-node tree-node--root ${started?"is-active":""}`} onClick={()=>setStarted(true)}><img src="/icons/raposa/fox_8907474.svg" alt=""/><b>{en?"Start":"Começar"}</b></button>{started&&!branch&&<div className="tree-branch-nodes">{BRANCHES.map(x=><button className="tree-node tree-node--branch" key={x.id} onClick={()=>setBranchId(x.id)}><img src={`/icons/raposa/${x.icon}`} alt=""/><b>{en?x.en:x.pt}</b></button>)}</div>}{branch&&<div className="tree-node tree-node--chosen-branch"><img src={`/icons/raposa/${branch.icon}`} alt=""/><b>{en?branch.en:branch.pt}</b></div>}{branch&&!service&&<div className="tree-service-nodes">{branch.nodes.map(x=><button className="tree-node tree-node--service" key={x.id} onClick={()=>setServiceId(x.id)}><img src={`/icons/raposa/${x.icon}`} alt=""/><b>{en?x.en:x.pt}</b></button>)}</div>}{service&&level===null&&<div className="tree-level-nodes">{LEVELS.map((x,i)=><button className="tree-node tree-node--level" key={x.pt} onClick={()=>setLevel(i)}><img src="/icons/raposa/fox_8729898.svg" alt=""/><b>{en?x.en:x.pt}</b></button>)}</div>}</div>{level!==null&&service&&<div className="tree-price"><span>{en?"Your estimated path":"Seu caminho estimado"}</span><strong>{money(total)}</strong><small>{en?service.en:service.pt} · {en?LEVELS[level].en:LEVELS[level].pt}</small><div><a href={`https://mail.google.com/mail/?view=cm&fs=1&to=andrilesteves%40gmail.com&body=${encodeURIComponent(summary)}`} target="_blank"><Mail/>{en?"Email quote":"Enviar por e-mail"}</a><a href={`https://wa.me/5541988635137?text=${encodeURIComponent(summary)}`} target="_blank"><MessageCircle/>{en?"WhatsApp quote":"Enviar por WhatsApp"}</a></div></div>}</section></div>;
}
