import { ArrowLeft, ArrowUpRight, Mail, MessageCircle } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import "../motion-scene.css";
import "../motion-carousel.css";

type ServiceId = "motion-video" | "branding-identidade" | "3d-cgi" | "criacao-de-sites";
type Case = { title:string; kind:string; image:string; href:string };
type Service = { id:ServiceId; number:string; title:string; short:string; accent:string; kicker:string; lead:string; services:string[]; process:string[]; cases:Case[]; faq:{q:string;a:string}[] };

const WHATSAPP = "https://wa.me/5541988635137?text=Oi%2C%20Andril!%20Quero%20conversar%20sobre%20um%20projeto.";
const img = {
  runtrip:"https://mir-s3-cdn-cf.behance.net/project_modules/hd/eef008256530173.6abe9e0dc59b8.png",
  talentos:"https://mir-s3-cdn-cf.behance.net/projects/404/51f95780504471.Y3JvcCwyMzY1LDE4NTAsMzA0LDA.jpg",
  peixe:"https://mir-s3-cdn-cf.behance.net/projects/404/2725b9195016255.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png",
  dog:"https://mir-s3-cdn-cf.behance.net/projects/404/fbd4d3187617213.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png",
  vineta:"https://mir-s3-cdn-cf.behance.net/projects/404/afc1a3157654809.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png",
  jobster:"https://mir-s3-cdn-cf.behance.net/projects/404/d20b27256534065.Y3JvcCwxMzA5LDEwMjQsMTEzLDA.jpg",
  ksenia:"https://mir-s3-cdn-cf.behance.net/projects/404/31df16256530935.Y3JvcCwxMjAzLDk0MSwyMzUsMA.png",
  hibiscus:"https://mir-s3-cdn-cf.behance.net/projects/404/c8a8f6163795319.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png",
  lata:"https://mir-s3-cdn-cf.behance.net/projects/404/edc588222736177.Y3JvcCwxMDgwLDg0NCwwLDUzNw.png",
  rocket:"https://mir-s3-cdn-cf.behance.net/projects/404/9c4075187617369.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png",
  boxxes:"https://mir-s3-cdn-cf.behance.net/projects/404/db6042136509355.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png",
  xadrez:"https://mir-s3-cdn-cf.behance.net/projects/404/44d8cd134872895.Y3JvcCw5NjUsNzU1LDg2LDA.png",
  web:"/incast-studio.png", frizz:"/mockups/refri-01.png", lua:"/mockups/beleza-01.png", aurelia:"/mockups/cosmeticos-01.png", uniterapy:"https://mir-s3-cdn-cf.behance.net/projects/404/80dbd591877299.Y3JvcCwxOTIwLDE1MDEsMCww.png"
};
const services:Service[] = [
  {id:"motion-video",number:"01",title:"MOTION\n& VÍDEO",short:"Motion & Vídeo",accent:"#ff267f",kicker:"MOVIMENTO COM PROPÓSITO",lead:"Da edição ao motion. Do corte ao impossível. Filmes, animação, pós-produção e VFX construídos para prender atenção.",services:["Motion design","Edição de vídeo","Pós-produção","VFX & compositing","Vídeos de campanha","Conteúdo para social","Video ads","Animação de identidade"],process:["Entender o ritmo, formato e objetivo.","Construir linguagem, timeline e direção visual.","Finalizar versões e formatos de entrega."],cases:[{title:"RUNTRIP",kind:"Motion design · IA",image:img.runtrip,href:"https://www.behance.net/gallery/256530173/RUNTRIP-Corrida-Turismo"},{title:"Intro Talentos",kind:"Vinheta · Motion graphics",image:img.talentos,href:"https://www.behance.net/gallery/80504471/Intro-Talentos"},{title:"Vineta",kind:"Vinheta · Motion graphics",image:img.vineta,href:"https://www.behance.net/gallery/157654809/Vineta"},{title:"Dog 3D",kind:"Teste de animação 3D",image:img.dog,href:"https://www.behance.net/gallery/187617213/Dog-3d-Test-Animation"},{title:"Peixe Procedural",kind:"Animação procedural",image:img.peixe,href:"https://www.behance.net/gallery/195016255/Peixe-Animacao-Procedural"},{title:"JOBSTER",kind:"Character 3D · Motion system",image:img.jobster,href:"https://www.behance.net/gallery/256534065/JOBSTER-3D-Character-Motion-System"}],faq:[{q:"Você edita material já gravado?",a:"Sim. A edição pode partir de material existente ou ser pensada junto com a direção visual e o motion."},{q:"Atende campanhas e conteúdo recorrente?",a:"Sim. O escopo pode ir de uma peça pontual a desdobramentos de campanha."}]},
  {id:"branding-identidade",number:"02",title:"BRANDING\n& IDENTIDADE",short:"Branding & Identidade",accent:"#ff7a1a",kicker:"SISTEMAS QUE CONTINUAM FUNCIONANDO",lead:"Uma marca não é um logo. É um sistema visual com presença, escala e consistência quando encontra o mundo.",services:["Identidade visual","Direção de arte","Sistemas de marca","Key visual","Campanhas","Motion branding","Peças digitais","Materiais gráficos"],process:["Mapear o que a marca precisa comunicar.","Definir linguagem, hierarquia e sistema.","Desdobrar para os pontos de contato necessários."],cases:[{title:"Frizz",kind:"Identidade · Embalagem",image:img.frizz,href:"/#content"},{title:"Lúa Skincare",kind:"Identidade · Direção de arte",image:img.lua,href:"/#content"},{title:"Aurélia",kind:"Branding · Embalagem",image:img.aurelia,href:"/#content"}],faq:[{q:"O projeto pode começar só por uma necessidade visual?",a:"Pode. A conversa inicial organiza o problema antes de decidir o tamanho do sistema."},{q:"Você cria aplicações além do logo?",a:"Sim. A identidade é pensada como conjunto de regras e aplicações, não como uma peça isolada."}]},
  {id:"3d-cgi",number:"03",title:"3D\n& CGI",short:"3D & CGI",accent:"#12d8e7",kicker:"IMAGENS QUE NÃO OBEDECEM AO MUNDO FÍSICO",lead:"CGI, animação e sistemas procedurais para produtos, campanhas e imagens que podem ir além do que uma câmera alcança.",services:["CGI para produto","Motion 3D","Procedural","Lookdev & render","Visualização de produto","Integração 3D / VFX","Assets digitais","Campanhas"],process:["Traduzir a ideia em cena, objeto ou sistema.","Modelar, desenvolver look e testar movimento.","Renderizar e finalizar para cada formato."],cases:[{title:"JOBSTER",kind:"Character 3D · Motion system",image:img.jobster,href:"https://www.behance.net/gallery/256534065/JOBSTER-3D-Character-Motion-System"},{title:"Procedural Hibiscus",kind:"Arte procedural · Blender",image:img.hibiscus,href:"https://www.behance.net/gallery/163795319/Procedural-Hibiscus"},{title:"Peixe Procedural",kind:"Animação procedural",image:img.peixe,href:"https://www.behance.net/gallery/195016255/Peixe-Animacao-Procedural"}],faq:[{q:"É possível criar produto antes de existir fisicamente?",a:"Sim. CGI permite visualizar, animar e testar uma presença visual antes da produção física."},{q:"Você trabalha com procedural?",a:"Sim. Sistemas procedurais fazem parte do repertório para criar comportamento, forma e variações."}]},
  {id:"criacao-de-sites",number:"04",title:"SITES\n& EXPERIÊNCIAS",short:"Criação de Sites",accent:"#a15cff",kicker:"DESIGN, MOVIMENTO E CÓDIGO",lead:"Design, movimento e código trabalhando juntos para apresentar uma marca e fazer as pessoas quererem explorar.",services:["Web design","Landing pages","Sites institucionais","Portfólios","Motion para web","Creative coding","Interfaces","Implementação front-end"],process:["Definir mensagem, conteúdo e percurso.","Desenhar interface, sistema e movimento.","Implementar, testar e publicar a experiência."],cases:[{title:"Incast Studio",kind:"Web design · Front-end",image:img.web,href:"https://incast-studio-978682563954.us-east1.run.app/"},{title:"Uniterapy",kind:"UI design · Protótipo",image:img.uniterapy,href:"https://www.behance.net/gallery/91877299/Prototipo-Uniterapy"}],faq:[{q:"Você faz só o design ou também implementa?",a:"O trabalho pode reunir design e implementação web quando o escopo pede uma experiência completa."},{q:"O site funciona no celular?",a:"Sim. A experiência é planejada para desktop e simplificada de forma responsável em telas menores."}]}
];

const threeD = services.find((service) => service.id === "3d-cgi");
if (threeD) threeD.cases = [
  {title:"KSENIA",kind:"Character 3D · Motion system",image:img.ksenia,href:"https://www.behance.net/gallery/256530935/KSENIA-Character-Design-Motion-System"},
  {title:"JOBSTER",kind:"Character 3D · Motion system",image:img.jobster,href:"https://www.behance.net/gallery/256534065/JOBSTER-3D-Character-Motion-System"},
  {title:"Lata",kind:"Render 3D",image:img.lata,href:"https://www.behance.net/gallery/222736177/Lata"},
  {title:"Procedural Hibiscus",kind:"Arte procedural · Blender",image:img.hibiscus,href:"https://www.behance.net/gallery/163795319/Procedural-Hibiscus"},
  {title:"Rocket",kind:"Render 3D",image:img.rocket,href:"https://www.behance.net/gallery/187617369/Rocket"},
  {title:"Boxxes",kind:"Render 3D",image:img.boxxes,href:"https://www.behance.net/gallery/136509355/Boxxes"},
  {title:"Xadrez",kind:"Render 3D",image:img.xadrez,href:"https://www.behance.net/gallery/134872895/Xadrez"},
  {title:"Peixe Procedural",kind:"Animação procedural",image:img.peixe,href:"https://www.behance.net/gallery/195016255/Peixe-Animacao-Procedural"}
];

const normalize=(path:string)=>path.replace(/\/+$/,"").split("/").filter(Boolean).at(-1) as ServiceId|"servicos"|undefined;
const go=(path:string)=>{window.history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));};

export default function ServicesPage(){
  const [path,setPath]=useState(()=>window.location.pathname); const reduce=useReducedMotion();
  const current=useMemo(()=>services.find(service=>service.id===normalize(path)),[path]);
  useEffect(()=>{const update=()=>setPath(window.location.pathname);window.addEventListener("popstate",update);return()=>window.removeEventListener("popstate",update);},[]);
  useEffect(()=>{
    const title=current?`${current.short} — Andrïl Esteves`:"Serviços — Andrïl Esteves";
    const description=current?.lead??"Motion, direção de arte, identidade visual, 3D, CGI e criação de sites para marcas, agências e estúdios.";
    const canonical=`https://andril.space${path.endsWith("/")?path:`${path}/`}`;
    document.title=title;
    document.querySelector('meta[name="description"]')?.setAttribute("content",description);
    document.querySelector('link[rel="canonical"]')?.setAttribute("href",canonical);
    document.querySelector('meta[property="og:title"]')?.setAttribute("content",title);
    document.querySelector('meta[property="og:description"]')?.setAttribute("content",description);
    document.querySelector('meta[property="og:url"]')?.setAttribute("content",canonical);
    document.querySelector('meta[name="twitter:title"]')?.setAttribute("content",title);
    document.querySelector('meta[name="twitter:description"]')?.setAttribute("content",description);
  },[current,path]);
  if(!current)return <main className="services-shell services-hub"><a className="services-back" href="/"><ArrowLeft/> ANDRIL</a><header className="services-hub__hero"><p className="code-label">/ universo comercial</p><h1>SERVIÇOS</h1><p>Uma pessoa. Várias linguagens.<br/>Motion, design, 3D e tecnologia para transformar ideias em experiências visuais.</p></header><section className="services-list" aria-label="Serviços"><p className="code-label">/ escolha um universo</p>{services.map(s=><button key={s.id} style={{"--service-accent":s.accent} as CSSProperties} onClick={()=>go(`/servicos/${s.id}/`)}><span>{s.number}</span><strong>{s.short}</strong><i>{s.kicker}</i><ArrowUpRight/></button>)}</section></main>;
  return <ServiceLanding service={current} reduce={Boolean(reduce)}/>;
}

function ServiceLanding({service,reduce}:{service:Service;reduce:boolean}){
  useAmbientCanvas(service,reduce);const style={"--service-accent":service.accent} as CSSProperties;
  const cases=service.id==="motion-video"?[...service.cases,...service.cases]:service.cases;
  return <main className={`service-page service-page--${service.id}`} style={style}><div className="service-atmosphere" aria-hidden="true"/><a className="services-back" href="/servicos/" onClick={e=>{e.preventDefault();go("/servicos/")}}><ArrowLeft/> SERVIÇOS</a><nav className="service-map" aria-label="Mapa de serviços">{services.map(item=><a className={item.id===service.id?"is-active":""} href={`/servicos/${item.id}/`} onClick={e=>{e.preventDefault();go(`/servicos/${item.id}/`)}} key={item.id}>{item.number}</a>)}</nav><motion.header className="service-hero" initial={reduce?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.6}}><p className="code-label">{service.number} / {service.kicker}</p><h1>{service.title.split("\n").map((line,i)=><span key={line}>{line}{i===0&&<br/>}</span>)}</h1><p>{service.lead}</p><div><a href={WHATSAPP} target="_blank" rel="noreferrer">CONTE SEU PROJETO <MessageCircle/></a><a href="#cases">VER CASOS <ArrowUpRight/></a></div></motion.header><FeatureScene service={service}/><section id="cases" className="service-block service-cases"><p className="code-label">01 / TRABALHOS SELECIONADOS</p><div className="case-rail">{cases.map((item,index)=><motion.a initial={reduce?false:{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:(index%service.cases.length)*.08}} href={item.href} target={item.href.startsWith("http")?"_blank":undefined} rel="noreferrer" key={`${item.title}-${index}`}><figure><img src={item.image} alt={`Projeto ${item.title} de Andril Esteves`} loading={index===0?"eager":"lazy"}/><span><ArrowUpRight/></span></figure><strong>{item.title}</strong><small>{item.kind}</small></motion.a>)}</div></section><section className="service-block service-offer"><p className="code-label">02 / O QUE POSSO FAZER</p><div>{service.services.map((item,index)=><motion.article key={item} initial={reduce?false:{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.025}}><span>{String(index+1).padStart(2,"0")}</span><h2>{item}</h2></motion.article>)}</div></section><section className="service-block service-process"><p className="code-label">03 / PROCESSO</p><div>{service.process.map((item,index)=><article key={item}><span>0{index+1}</span><p>{item}</p></article>)}</div></section><section className="service-block service-faq"><p className="code-label">04 / FAQ</p>{service.faq.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</section><footer className="service-cta"><p>BASEADO EM CURITIBA.<br/>REMOTE / WORLDWIDE.</p><h2>VAMOS<br/><em>conversar.</em></h2><div><a href="mailto:andrilesteves@gmail.com"><Mail/> EMAIL</a><a href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> WHATSAPP</a></div></footer></main>;
}

function FeatureScene({service}:{service:Service}){
  if(service.id==="motion-video")return <section className="feature-scene feature-motion"><div className="motion-field" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="motion-statement"><small>MOTION / EDIT / VFX</small><strong>IDEIAS<br/><em>em</em> movimento.</strong><p>Uma composição viva que muda de forma,<br/>ritmo e direção.</p></div><span className="motion-index">01—30</span></section>;
  if(service.id==="branding-identidade")return <section className="feature-scene feature-brand"><div className="brand-copy"><small>IDENTITY<br/>SYSTEM</small><strong>F<br/><em>R</em><br/>I<br/>Z<br/>Z</strong></div><figure><img src={img.frizz} alt="Projeto Frizz"/></figure><p>Uma identidade não para no logo.<br/>Ela continua no produto, no espaço e no detalhe.</p></section>;
  if(service.id==="3d-cgi")return <section className="feature-scene feature-3d"><figure><img src={img.jobster} alt="Projeto Jobster"/></figure><div><small>FORM / LIGHT / MOTION</small><strong>3D<br/><em>que</em> ganha<br/>vida.</strong></div><p>Do objeto ao personagem:<br/>forma, matéria, luz e movimento.</p></section>;
  return <section className="feature-scene feature-web"><div className="web-window"><header><i/><i/><i/><span>andril.space / experience</span></header><img src={img.web} alt="Site Incast Studio desenvolvido por Andril Esteves"/></div><p>Interfaces que respondem.<br/>Não só páginas que informam.</p><small>SCROLL · HOVER · MOTION · CODE</small></section>;
}

function useAmbientCanvas(service:Service,reduce:boolean){useEffect(()=>{if(reduce||service.id==="motion-video"||window.matchMedia("(max-width: 820px)").matches)return;const host=document.querySelector<HTMLElement>(".service-page .service-atmosphere");if(!host)return;const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");if(!ctx)return;canvas.className="service-canvas";host.appendChild(canvas);let w=0,h=0,raf=0;const pts=Array.from({length:service.id==="criacao-de-sites"?60:42},()=>({x:Math.random(),y:Math.random(),dx:(Math.random()-.5)*.00028,dy:(Math.random()-.5)*.00028}));const size=()=>{w=host.clientWidth;h=host.clientHeight;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);};const draw=(t:number)=>{ctx.clearRect(0,0,w,h);if(service.id==="branding-identidade"){for(let i=0;i<13;i++){ctx.strokeStyle=service.accent;ctx.globalAlpha=.09;ctx.lineWidth=1;ctx.strokeRect((i%4)*w*.25+Math.sin(t*.0003+i)*12,Math.floor(i/4)*h*.28,w*.19,h*.17);}}else{pts.forEach(a=>{a.x+=a.dx;a.y+=a.dy;if(a.x<0||a.x>1)a.dx*=-1;if(a.y<0||a.y>1)a.dy*=-1;ctx.beginPath();ctx.arc(a.x*w,a.y*h,service.id==="3d-cgi"?1.7:1,0,Math.PI*2);ctx.fillStyle=service.accent;ctx.globalAlpha=.34;ctx.fill();});for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],d=Math.hypot((a.x-b.x)*w,(a.y-b.y)*h);if(d<120){ctx.beginPath();ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.strokeStyle=service.accent;ctx.globalAlpha=.11*(1-d/120);ctx.stroke();}}}ctx.globalAlpha=1;raf=requestAnimationFrame(draw);};size();addEventListener("resize",size);raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",size);canvas.remove();};},[service,reduce]);}
